USE [Festivos];
GO
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS ORDER BY TABLE_NAME, ORDINAL_POSITION;
SELECT * FROM dbo.TipoFestivo;
SELECT * FROM dbo.Pais;
SELECT * FROM dbo.Festivo ORDER BY IdPais, Id;
